export const MANNEQUINS_DATA = [
  { nom: "ABESSOLO Alix", username: "Man-PMMA09", password: "abessolo2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "AJ Caramela", username: "Man-PMMA04", password: "aj2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Akoma Ayo Rosnel", username: "Man-PMMA01", password: "akoma2025", niveau: "Pro", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Alli li 19", username: "Man-PMMA05", password: "allili2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Anani Donatien", username: "Man-PMMA03", password: "anani2025", niveau: "Pro", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Anne PADOU", username: "Man-PMMA12", password: "anne2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Annie Flora", username: "Man-PMMA02", password: "annie2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Arléna ANGOUET", username: "Man-PMMA06", password: "arlena2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Aurore KONE", username: "Man-PMMA07", password: "aurore2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Benga Sadia", username: "Man-PMMB01", password: "benga2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Blanche Armancia EKEWA DEACKEN", username: "Man-PMMB02", password: "blanchearmancia2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Cassandra Ibouanga", username: "Man-PMMC01", password: "cassandra2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Cegolaine Biye", username: "Man-PMMC02", password: "cegolaine2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Chafyda MOUSSAVOU SWALEHE", username: "Man-PMMC03", password: "chafyda2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Christy NGOUA", username: null, password: null, niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Diane TCHIBNDA", username: "Man-PMMD06", password: "diane2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Diane Vanessa", username: "Man-PMMD01", password: "diane2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Dorcas SAPHOU", username: "dorcas.saphou", password: "dorcas2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Doria rosina MOUTSINGA LEWOBI", username: "Man-PMMD04", password: "doriarosina2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Emmanuelle Maballi", username: "Man-PMME05", password: "emmanuelle2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Essono Lea Danielle", username: "Man-PMME01", password: "essono2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Esther MBINA", username: "Man-PMME04", password: "esther2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Esther Esapie", username: "Man-PMME03", password: "esther2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Eunice", username: "eunice", password: "eunice2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "GNIOBO Arselia", username: "Man-PMMG01", password: "gniobo2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Hawa MOUNDENI", username: "Man-PMMH02", password: "hawa2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Hurielle Kerenne", username: "Man-PMMH01", password: "hurielle2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Janiéla Nguema", username: "Man-PMMJ01", password: "janiela2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "KEGNIA OMPOKI Dousca Wesly", username: "Man-PMMK03", password: "kegniaompoki2025", niveau: "Pro", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Kendra Mebiame", username: "Man-PMMK02", password: "kendra2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "KEVINE Moussavou", username: "Man-PMMK04", password: "kevine2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Khelany Allogho", username: "Man-PMMK01", password: "khelany2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "KOUNA Asnath Chelsea", username: "Man-PMMK05", password: "kouna2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Laure SEKE", username: "Man-PMML04", password: "laure2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Lesly Zomo", username: "Man-PMML01", password: "lesly2025", niveau: "Débutant", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Lorielna MOUNGUENGUI", username: "Man-PMML02", password: "lorielna2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Lucresse SENDZE", username: "Man-PMML05", password: "lucresse2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Maïra Ayang Ndong", username: "Man-PMMM07", password: "maira2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Marisca BIVIGOU", username: null, password: null, niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Mbazoghe Latifa Nynelle", username: "Man-PMMM02", password: "mbazoghe2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Moustapha", username: "Man-PMMM04", password: "moustapha2025", niveau: "Débutant", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Nahoumie MABILA", username: "Man-PMMN05", password: "nahoumie2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Ndinga ibouanga Brice yowane", username: "Man-PMMN06", password: "ndingaibouanga2025", niveau: "Débutant", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Nelly Rose Nse Allogo", username: "Man-PMMN07", password: "nellyrose2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Noé Mak's", username: "Man-PMMN04", password: "noe2025", niveau: "Débutant", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Noemi Kim", username: "Man-PMMN03", password: "noemi2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "NYAMETE TOWENE Ruth Jussy", username: "Man-PMMN01", password: "nyamete2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Osée Jn", username: "Man-PMMO02", password: "osee2025", niveau: "Pro", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Raida Katsini", username: "Man-PMMR02", password: "raida2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Raïna NTSAME", username: "Man-PMMR06", password: "raina2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Raïva MONDJO", username: "Man-PMMR05", password: "raiva2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Rosly Emmanuel Eya biyogho", username: "Man-PMMR03", password: "roslyemmanuel2025", niveau: "Débutant", genre: "Homme", public: true, location: "Libreville" },
  { nom: "Ruth Ella", username: "Man-PMMR01", password: "ruth2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Ruth danicia Nweninga", username: "Man-PMMR07", password: "ruthdanicia2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Samantha Abong obiang", username: "Man-PMMS03", password: "samantha2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Sarah KLOMEGAN", username: null, password: null, niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Sephora Nawelle", username: "Man-PMMS01", password: "sephora2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Stecy Glappier", username: "Man-PMMS02", password: "stecy2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Stephie NDOMBI", username: "Man-PMMS06", password: "stephie2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Styna MOUTSINGA", username: "Man-PMMS07", password: "styna2025", niveau: "Pro", genre: "Femme", public: true, location: "Libreville" },
  { nom: "Ursula BOUMSO", username: "Man-PMMU01", password: "ursula2025", niveau: "Débutant", genre: "Femme", public: true, location: "Libreville" },
];
