mutation CreateNewTask($title: String!, $description: String, $dueDate: Date, $isCompleted: Boolean!) @auth(level: USER) {
  task_insert(data: {
    title: $title,
    description: $description,
    dueDate: $dueDate,
    isCompleted: $isCompleted,
    userId_expr: "auth.uid"
  })
}

query GetMyTasks @auth(level: USER) {
  tasks(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    title
    description
    dueDate
    isCompleted
  }
}

mutation UpdateTaskCompletion($id: UUID!, $isCompleted: Boolean!) @auth(level: USER) {
  task_update(
    id: $id,
    data: {
      isCompleted: $isCompleted
    }
  )
}

query ListAllUsers @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  users {
    id
    displayName
    email
  }
}