type User @table {
  displayName: String!
  email: String
  createdAt: Timestamp!
}

type Task @table {
  title: String!
  description: String
  dueDate: Date
  isCompleted: Boolean!
  createdAt: Timestamp!
  user: User
}

type Tag @table {
  name: String!
  createdAt: Timestamp!
  user: User
}

type TaskTag @table(key: ["task", "tag"]) {
  task: Task!
  tag: Tag!
}